---
- name: Fedora Post-Install Setup - Stage 4 - Hardware Specific & Third-Party Apps
  hosts: localhost
  become: yes
  vars_files:
    - vars/main.yml

  tasks:
    # --- ASUS ROG Setup ---
    - name: Hardware | Detect ASUS System
      set_fact:
        is_asus: "{{ (ansible_system_vendor | default('') | lower is search('asus')) or (ansible_board_vendor | default('') | lower is search('asus')) }}"
      tags: [hardware, asus]

    - name: System | Detect Desktop Environment
      set_fact:
        detected_xdg: "{{ lookup('env', 'XDG_CURRENT_DESKTOP') | default('') | upper }}"
      tags: [system, detection]

    - name: System | Set DE Boolean Facts
      set_fact:
        is_gnome: "{{ 'GNOME' in detected_xdg }}"
        is_kde: "{{ 'KDE' in detected_xdg or 'PLASMA' in detected_xdg }}"
      tags: [system, detection]

    - name: Shell | Get home directory of the primary user
      ansible.builtin.getent:
        database: passwd
        key: "{{ ansible_env.SUDO_USER }}"
      register: primary_user_data
      when: ansible_env.SUDO_USER is defined and ansible_env.SUDO_USER != 'root'
      tags: [system, asus]

    - name: Hardware | Enable ASUS ROG Copr Repository
      community.general.copr:
        name: "{{ asus_copr_repo }}"
        state: enabled
      #when: is_asus
      tags: [hardware, asus]

    - name: Hardware | Refresh DNF Cache for COPR
      ansible.builtin.dnf:
        update_cache: yes
      when: is_asus
      tags: [hardware, asus]

    - name: Hardware | Install ASUS ROG Packages
      ansible.builtin.dnf:
        name: "{{ asus_packages }}"
        state: present
      when: is_asus
      tags: [hardware, asus]


    - name: Hardware | Enable and Start supergfxd.service
      ansible.builtin.systemd:
        name: supergfxd.service
        enabled: yes
        state: started
      when: is_asus
      tags: [hardware, asus]

    - name: Hardware | Ensure Autostart Directory Exists
      ansible.builtin.file:
        path: "{{ primary_user_data.ansible_facts.getent_passwd[ansible_env.SUDO_USER][4] }}/.config/autostart"
        state: directory
        owner: "{{ ansible_env.SUDO_USER }}"
        group: "{{ ansible_env.SUDO_USER }}"
        mode: '0755'
      when: is_asus and ansible_env.SUDO_USER is defined
      tags: [hardware, asus]

    - name: Hardware | Add ASUS ROG GUI to Autostart
      ansible.builtin.copy:
        src: "/usr/share/applications/rog-control-center.desktop"
        dest: "{{ primary_user_data.ansible_facts.getent_passwd[ansible_env.SUDO_USER][4] }}/.config/autostart/rog-control-center.desktop"
        remote_src: yes
        owner: "{{ ansible_env.SUDO_USER }}"
        group: "{{ ansible_env.SUDO_USER }}"
        mode: '0644'
      when: is_asus and ansible_env.SUDO_USER is defined
      tags: [hardware, asus]
